service: "bang-the-mug-all-day"

useDotenv: true

provider:
  name: aws
  region: us-east-2
  runtime: nodejs16.x
  environment:
    TWITTER_API_KEY: ${env:TWITTER_API_KEY}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    TWITTER_SECRET: ${env:TWITTER_SECRET}

functions:
  daily-post:
    handler: index.handler
    timeout: 180
    events:
      - schedule: cron(0 16 ? * MON-FRI *)

  # callback:
  #   handler: index.callback
  #   events:
  #     - http:
  #         path: /callback
  #         method: GET

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
